// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package batch

import (
	"context"
)

type Querier interface {
	Delete(ctx context.Context, names []string) ([]string, error)
	Get(ctx context.Context, names []string) ([]Key, error)
}

var _ Querier = (*Queries)(nil)
