// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package writers

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddFloat(ctx context.Context, arg *AddFloatParams) (float64, error)
	AddInt(ctx context.Context, arg *AddIntParams) (int64, error)
	AppendValue(ctx context.Context, arg *AppendValueParams) (sql.NullInt64, error)
	FlushAll(ctx context.Context) error
	ListRightPush(ctx context.Context, arg *ListRightPushParams) (ListRightPushRow, error)
	ListRightPushUpsert(ctx context.Context, arg *ListRightPushUpsertParams) (ListRightPushUpsertRow, error)
	ListSet(ctx context.Context, arg *ListSetParams) (interface{}, error)
	Set(ctx context.Context, arg *SetParams) error
}

var _ Querier = (*Queries)(nil)
