// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package readers

import (
	"context"
)

type Querier interface {
	Get(ctx context.Context, name string) (string, error)
	Substr(ctx context.Context, arg *SubstrParams) (string, error)
}

var _ Querier = (*Queries)(nil)
