// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: readers.sql

package readers

import (
	"context"
)

const get = `-- name: Get :one
SELECT value
FROM strings
WHERE name = ?1
`

func (q *Queries) Get(ctx context.Context, name string) (string, error) {
	row := q.queryRow(ctx, q.getStmt, get, name)
	var value string
	err := row.Scan(&value)
	return value, err
}
